# Generated by Django 2.1.1 on 2018-10-18 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0005_auto_20181015_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixelevent',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='pixelevent',
            name='utm_content',
        ),
        migrations.RemoveField(
            model_name='pixelevent',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='pixelevent',
            name='utm_source',
        ),
        migrations.RemoveField(
            model_name='pixelevent',
            name='utm_term',
        ),
        migrations.AddField(
            model_name='pixelevent',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
