# Generated by Django 2.1.1 on 2018-10-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0008_auto_20181018_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pixelevent',
            name='params',
        ),
        migrations.RemoveField(
            model_name='pixelevent',
            name='url',
        ),
    ]
